### ISSUE TITLE
Avoid re-importing existing manifest

### ISSUE THREAD

**Issue by stdevel** [RedHatOfficial/ansible-role-redhat_satellite6_installation#30]
It would be great to have the possibility to skip re-uploading an manifest, cause otherwise the following error will occur:
```
Error: Import is the same as existing data
```

Full stacktrace:
```
TASK [redhat_satellite6_installation : Configure | upload the manifest] ********
fatal: [satellite]: FAILED! => {"changed": true, "cmd": "hammer subscription upload --file /root/satellite_manifest.zip --organization ACME", "delta": "0:00:16.749160", "end": "2019-10-24 05:43:51.015606", "msg": "non-zero return code", "rc": 70, "start": "2019-10-24 05:43:34.266446", "stderr": "warning: Overriding \"Content-Type\" header \"multipart/form-data\" with \"multipart/form-data; boundary=----RubyFormBoundaryd8OqKFdfDuw3hljk\" due to payload\nTask c5a21aea-7d11-42df-b722-7516d557355b planned: 0.0/1, 0%, elapsed: 00:00:00\nTask c5a21aea-7d11-42df-b722-7516d557355b running: 0.0/1, 0%, 0.0/s, elapsed: 00:00:02\nTask c5a21aea-7d11-42df-b722-7516d557355b running: 0.0/1, 0%, 0.0/s, elapsed: 00:00:04\nTask c5a21aea-7d11-42df-b722-7516d557355b running: 0.0/1, 0%, 0.0/s, elapsed: 00:00:06\nTask c5a21aea-7d11-42df-b722-7516d557355b running: 0.25/1, 25%, 0.0/s, elapsed: 00:00:08, ETA: 00:00:24\nTask c5a21aea-7d11-42df-b722-7516d557355b running: 0.375/1, 37%, 0.0/s, elapsed: 00:00:10, ETA: 00:00:17\nTask c5a21aea-7d11-42df-b722-7516d557355b running: 0.625/1, 62%, 0.1/s, elapsed: 00:00:12, ETA: 00:00:07\nTask c5a21aea-7d11-42df-b722-7516d557355b warning: 1.0/1, 100%, 0.1/s, elapsed: 00:00:14\nTask c5a21aea-7d11-42df-b722-7516d557355b warning: 1.0/1, 100%, 0.1/s, elapsed: 00:00:14\nError: Import is the same as existing data", "stderr_lines": ["warning: Overriding \"Content-Type\" header \"multipart/form-data\" with \"multipart/form-data; boundary=----RubyFormBoundaryd8OqKFdfDuw3hljk\" due to payload", "Task c5a21aea-7d11-42df-b722-7516d557355b planned: 0.0/1, 0%, elapsed: 00:00:00", "Task c5a21aea-7d11-42df-b722-7516d557355b running: 0.0/1, 0%, 0.0/s, elapsed: 00:00:02", "Task c5a21aea-7d11-42df-b722-7516d557355b running: 0.0/1, 0%, 0.0/s, elapsed: 00:00:04", "Task c5a21aea-7d11-42df-b722-7516d557355b running: 0.0/1, 0%, 0.0/s, elapsed: 00:00:06", "Task c5a21aea-7d11-42df-b722-7516d557355b running: 0.25/1, 25%, 0.0/s, elapsed: 00:00:08, ETA: 00:00:24", "Task c5a21aea-7d11-42df-b722-7516d557355b running: 0.375/1, 37%, 0.0/s, elapsed: 00:00:10, ETA: 00:00:17", "Task c5a21aea-7d11-42df-b722-7516d557355b running: 0.625/1, 62%, 0.1/s, elapsed: 00:00:12, ETA: 00:00:07", "Task c5a21aea-7d11-42df-b722-7516d557355b warning: 1.0/1, 100%, 0.1/s, elapsed: 00:00:14", "Task c5a21aea-7d11-42df-b722-7516d557355b warning: 1.0/1, 100%, 0.1/s, elapsed: 00:00:14", "Error: Import is the same as existing data"], "stdout": "", "stdout_lines": []}
```

**Comment by ghost** [comment]
---
#Create Hammer directory on /root
- name: "Configure | create .hammer directory on user"
  file:
    path: "~/.hammer"
    state: "directory"
    mode: "0755"

#Copy the hammer configuration from template to the .hammer directory
- name: "Configure | set configuration for hammer from template"
  template:
    src: "hammer_config.yml.j2"
    dest: "~/.hammer/cli_config.yml"

#Copy the manifest
- name: "Configure | copy manifest"
  become: "yes"
  copy:
    src: "{{ satellite_deployment_manifest_path }}"
    dest: "{{ satellite_deployment_manifest_dest_path }}"
  when: satellite_deployment_remote_manifest is undefined
  #when: not satellite_deployment_remote_manifest

- name: "Configure | copy manifest from remote"
  become: "yes"
  get_url:
    url: "{{ satellite_deployment_manifest_path }}"
    dest: "{{ satellite_deployment_manifest_dest_path }}"
  when: satellite_deployment_remote_manifest is not undefined

#Fetch organization ID
- name: "Check | fetch organization ID"
  become: "yes"
  shell: "hammer organization list | grep {{ satellite_deployment_organization }} | cut -d '|' -f 1"
  register: id
  ignore_errors: True

#If fetching organization ID failed display the message
- name: "Check | fetching of organization ID if failed"
  command: /bin/echo "Unable to fetch Organization list."
  when: id is failed

#Type casting id to number
- name: "Set fact for organization ID"
  set_fact:
    organization_id: "{{ id.stdout | int }}"
  when: id is succeeded

- name: "Check succeeded"
  shell: "hammer subscription manifest-history --organization-id {{ organization_id }} | grep -i SUCCESS"
  register: manifest_status
  when: id is succeeded

#Upload the manifest to the satellite
- name: "Configure | upload the manifest"
  become: "yes"
  shell: "hammer subscription upload --file
    {{ satellite_deployment_manifest_dest_path }} --organization
    {{ satellite_deployment_organization }}"
  when: manifest_status is not succeeded  

#Enabling repos on satellite
- name: "Configure | enable repos"
  become: "yes"
  shell: "hammer repository-set '{{ item.state }}' --organization
    '{{ satellite_deployment_organization }}'
    --product '{{ item.product_name }}' --name '{{ item.name_repo }}'
    {% if item.rel is defined %} --releasever '{{ item.rel }}' {% endif %}
    --basearch '{{ item.architecture}}'"
  with_items: "{{ satellite_deployment_repositories }}"
  ignore_errors: "yes"
  tags:
    - "satellite_deployment_repositories"

#Get the repos ids and sync the repos
- name: "Configure | grab repositories uuid"
  shell: "hammer repository list --organization
    {{ satellite_deployment_organization }} | grep yum | awk '{print $1}'"
  register: "repos"

- name: "Configure | sync repos on satellite"
  shell: "hammer repository synchronize --id '{{ item }}' --organization
    {{ satellite_deployment_organization }}"
  with_items: "{{ repos.stdout_lines }}"
  register: "sync_repos_result"
  retries: 3
  until: "{{ sync_repos_result | success }}"

**Comment by stdevel** [comment]
Thanks for sharing, @ketogs - that looks great, works like a charm for my Satellite 6.6 Vagrant box:
```
TASK [redhat_satellite6_installation : Configure | copy manifest] **************
skipping: [satellite]

TASK [redhat_satellite6_installation : Configure | copy manifest from remote] ***
ok: [satellite]

TASK [redhat_satellite6_installation : Check | fetch organization ID] **********
changed: [satellite]

TASK [redhat_satellite6_installation : Check | fetching of organization ID if failed] ***
skipping: [satellite]

TASK [redhat_satellite6_installation : Set fact for organization ID] ***********
ok: [satellite]

TASK [redhat_satellite6_installation : Check succeeded] ************************
changed: [satellite]

TASK [redhat_satellite6_installation : Configure | upload the manifest] ********
skipping: [satellite]
```

Just created PR #33 for this.
